-- https://www.hackerrank.com/challenges/the-company/problem

SELECT
    COMPANY.COMPANY_CODE,
    COMPANY.FOUNDER,
    COUNT(DISTINCT LEAD_MANAGER.LEAD_MANAGER_CODE),
    COUNT(DISTINCT SENIOR_MANAGER.SENIOR_MANAGER_CODE),
    COUNT(DISTINCT MANAGER.MANAGER_CODE),
    COUNT(DISTINCT EMPLOYEE.EMPLOYEE_CODE)
FROM
    COMPANY
LEFT JOIN LEAD_MANAGER
    ON COMPANY.COMPANY_CODE = LEAD_MANAGER.COMPANY_CODE
LEFT JOIN SENIOR_MANAGER
    ON LEAD_MANAGER.LEAD_MANAGER_CODE = SENIOR_MANAGER.LEAD_MANAGER_CODE
LEFT JOIN MANAGER
    ON SENIOR_MANAGER.SENIOR_MANAGER_CODE = MANAGER.SENIOR_MANAGER_CODE
LEFT JOIN EMPLOYEE
    ON MANAGER.MANAGER_CODE = EMPLOYEE.MANAGER_CODE
GROUP BY
    COMPANY.COMPANY_CODE,
    COMPANY.FOUNDER
ORDER BY
    COMPANY.COMPANY_CODE ASC;